config/routes.rb
Rails.application.routes.draw do
  get '/cocktail_recipes', to: 'cocktail_recipes#index', as: 'cocktail_recipes'
  get '/cocktail_recipes/new', to: 'cocktail_recipes#new', as: 'new_cocktail_recipe'
  post '/cocktail_recipes', to: 'cocktail_recipes#create'
  get '/cocktail_recipes/:id', to: 'cocktail_recipes#show', as: 'cocktail_recipe'
  get '/cocktail_recipes/:id/edit', to: 'cocktail_recipes#edit', as: 'edit_cocktail_recipe'
  patch '/cocktail_recipes/:id', to: 'cocktail_recipes#update'
  delete '/cocktail_recipes/:id', to: 'cocktail_recipes#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail_recipe.rb
class CocktailRecipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktail_recipes_controller.rb
class CocktailRecipesController < ApplicationController

  def index
    @cocktail_recipes = CocktailRecipe.all
  end

  def new
    @cocktail_recipe = CocktailRecipe.new
  end

  def create
    cocktail_recipe_params = params.require(:cocktail_recipe).permit(:name, :recipe, :creator)
    @cocktail_recipe = CocktailRecipe.create(cocktail_recipe_params)
    redirect_to cocktail_recipe_path(@cocktail_recipe)
  end

  def show
    @cocktail_recipe = CocktailRecipe.find(params[:id])
  end

  def edit
    @cocktail_recipe = CocktailRecipe.find(params[:id])
  end

  def update
    cocktail_recipe = CocktailRecipe.find(params[:id])
    cocktail_recipe_params = params.require(:cocktail_recipe).permit(:name, :recipe, :creator)
    cocktail_recipe.update(cocktail_recipe_params)
    redirect_to cocktail_recipe_path(cocktail_recipe)
  end

  def destroy
    @cocktail_recipe = CocktailRecipe.find(params[:id])
    @cocktail_recipe.destroy!
    redirect_to cocktail_recipes_path, :notice => "Your cocktail has been deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_recipes_helper.rb
module CocktailRecipesHelper
end

app/views/cocktail_recipes/edit.html.erb
h1> Edit your recipe </h1>
<p><%= form_for @cocktail_recipe  do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %><br/>
    <%= f.label :recipe %>
    <%= f.text_area :recipe %><br/>
    <%= f.label :creator %>
    <%= f.text_field :creator %><br/>
    <%= f.submit "Submit" %>
<% end %>
</p>

app/views/cocktail_recipes/index.html.erb
<h1> Cocktail Recipes </h1>
  <% @cocktail_recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %></li>
    <% end %>

app/views/cocktail_recipes/new.html.erb
<h1> Create a new recipe </h1>
<p><%= form_for @cocktail_recipe  do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %><br/>
    <%= f.label :recipe %>
    <%= f.text_area :recipe %><br/>
    <%= f.label :creator %>
    <%= f.text_field :creator %><br/>
    <%= f.submit "Submit" %>
<% end %>
</p>

app/views/cocktail_recipes/show.html.erb
<h1><%= @cocktail_recipe.name %></h1>
<p><%= @cocktail_recipe.recipe %><br>
   <%= @cocktail_recipe.creator %>
   <%= button_to "Edit", edit_cocktail_recipe_path(@cocktail_recipe), :method => :get %>
   <%= button_to "Delete", @cocktail_recipe, :method => :delete %>
</p>
<nav>
    <%= link_to "Go back", cocktail_recipes_path%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CocktailRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>